version: 3
output: prefixed
tasks:
  build:
    desc: Build the binary
    deps: [generate]
    cmds:
      - go build -ldflags "-s -w -X=github.com/algolia/cli/pkg/version.Version={{ .VERSION }}" -o algolia cmd/algolia/main.go
    vars:
      VERSION: main
  generate:
    desc: Generate command flags
    internal: true
    cmds:
      - go generate ./...
  test:
    desc: Run unit tests
    run: always
    cmds:
      - go test ./...
  lint:
    desc: Lint code
    cmds:
      - golangci-lint run
  format:
    desc: Format code
    cmds:
      - gofumpt -w pkg cmd test internal api
      - golines -w pkg cmd test internal api
  ci:
    desc: Run everything
    aliases:
      - default
    deps:
      - build
      - test
      - lint
