name: Scheduled API Specs Pull Request
on:
  pull_request:

jobs:
  api-specs-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          git config --global user.name "algolia-ci"
          git config --global user.email "noreply@algolia.com"
      - run: make api-specs-pr
        env:
          GH_TOKEN: ${{ secrets.GH_SECRET }}