name: Scheduled API Specs Pull Request
on:
  schedule:
    - cron: '0 */12 * * *'

jobs:
  api-specs-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - run: |
          git config --global user.name "algolia-ci"
          git config --global user.email "noreply@algolia.com"
      - run: make api-specs-pr
        env:
          GH_TOKEN: ${{ secrets.GH_SECRET }}